Updated README.md
SlotNSlot/SlotNSlot pull request #164
Opened 2017-08-09 12:59 UTC by fish-sushi

2017-08-09 13:02 UTC, c0smic0wl commented on README.md
> +geth --testnet --syncmode=full --rpc --shh --networkid=3 --unlock [account] console
`--unlock [index]` can also unlock the account. I think `--unlock 0` is easier.

2017-08-09 13:03 UTC, c0smic0wl approved these changes
:owl:

2017-08-10 12:22 UTC, parkkoon requested changes

2017-08-10 12:22 UTC, parkkoon commented on README.md
> +geth --testnet --syncmode=full --rpc --shh --networkid=3 --unlock [account] console
full -> fast

2017-08-10 12:22 UTC, parkkoon commented on README.md
> +geth --testnet --syncmode=fast --rpc --shh --networkid=3 console
Maybe we will not use ropsten. Replace 3 to 4 please.

2017-08-11 11:26 UTC, merged