Fix for breakaway
SlotNSlot/SlotNSlot pull request #183
Opened 2017-08-13 17:49 UTC by parkkoon

2017-08-13 18:06 UTC, fish-sushi requested changes

2017-08-13 18:06 UTC, fish-sushi commented on app/javascripts/components/playSlot/actions.jsx
> +      await dispatch({
?

2017-08-13 18:06 UTC, fish-sushi commented on app/javascripts/components/playSlot/actions.jsx
> +      await dispatch({
?

2017-08-14 01:24 UTC, c0smic0wl approved these changes
:owl:

2017-08-14 01:25 UTC, merged