Fix about main
SlotNSlot/SlotNSlot pull request #47
Opened 2017-07-12 15:32 UTC by c0smic0wl

- Add Countdown Section for ICO.
- Add Medium Link.
- Fix some responsible css issues.

2017-07-12 15:32 UTC, c0smic0wl commented on app/javascripts/components/about/crowdSaleContainer/crowdSaleContainer.jsx
> +    // pass
Ah.. I'll remove it.

2017-07-12 15:45 UTC, parkkoon approved these changes
👍

2017-07-12 15:45 UTC, parkkoon commented on app/javascripts/components/about/crowdSaleContainer/crowdSaleContainer.jsx
> +    // console.log(this.props.aboutCrowdSale.get('dueDate'));
Please remove this, too.

2017-07-13 10:37 UTC, fish-sushi requested changes

2017-07-13 10:37 UTC, fish-sushi commented on app/javascripts/components/about/crowdSaleContainer/crowdSaleContainer.jsx
> +    this.interval = setInterval(this.updateTimer, 500);
👍

2017-07-13 10:37 UTC, fish-sushi commented on app/javascripts/components/about/crowdSaleContainer/crowdSaleContainer.jsx
> +    clearInterval(this.interval);
💯

2017-07-13 10:37 UTC, fish-sushi commented on app/javascripts/icons/crowdsale-ticket.svg
> +        <path id="b" d="M1566 542.599v48.545c0 13.728-11.128 24.856-24.856 24.856h-341.78c-.297-34.41-30.698-62.219-68.158-62.219s-67.861 27.81-68.158 62.219H24.856C11.128 616 0 604.872 0 591.144V542
Change id

2017-07-13 11:02 UTC, merged