Calculate slot line
SlotNSlot/SlotNSlot pull request #61
Opened 2017-07-16 13:03 UTC by parkkoon

Add naive calculate algorithm & slot logic complete
Change variable naming and state check while changing status
Calculate same symbol & slot Lines with min distance for avoiding inconsistency.
Connect winMoney & winMoneyText
Add WIN_LINE_COLOR

2017-07-16 15:10 UTC, fish-sushi requested changes

2017-07-16 15:10 UTC, fish-sushi commented on app/javascripts/components/playSlot/game.jsx
> +    const j = Math.floor(Math.random() * i);
This won't make random index.
I think you should use Math.floor(Math.random() * arr.length);
or you can use [Lodash's shuffle method](https://www.npmjs.com/package/lodash.shuffle).

2017-07-16 15:11 UTC, fish-sushi commented
I'll review the rest tomorrow

2017-07-17 04:52 UTC, parkkoon commented on app/javascripts/components/playSlot/game.jsx
> +    const j = Math.floor(Math.random() * i);
OK I will use that method.

2017-07-17 13:39 UTC, c0smic0wl approved these changes
🦉

2017-07-17 14:35 UTC, fish-sushi approved these changes
🍶

2017-07-17 14:35 UTC, merged